"""create governance_runs and governance_events

Revision ID: 3e36f74c2002
Revises: 
Create Date: 2026-10-01 00:06:18.947969
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3e36f74c2002'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_version', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('governance_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), server_default='tool_action', nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.String(length=255), nullable=False),
    sa.Column('arguments_sanitized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('arguments_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['governance_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_governance_events_created_at', 'governance_events', ['created_at'], unique=False)
    op.create_index('idx_governance_events_decision', 'governance_events', ['decision'], unique=False)
    op.create_index('idx_governance_events_run_id', 'governance_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_governance_events_run_id', table_name='governance_events')
    op.drop_index('idx_governance_events_decision', table_name='governance_events')
    op.drop_index('idx_governance_events_created_at', table_name='governance_events')
    op.drop_table('governance_events')
    op.drop_table('governance_runs')
    # ### end Alembic commands ###
